ssh:
  banner: "Welcome to the Custom ContainerSSH Guest Environment!\n"
  hostkeys:
    - "/etc/containerssh/host.key"

backend: docker

docker:
  connection:
    host: "unix:///var/run/docker.sock"
  execution:
    container:
      image: "attack_playground_image:latest"
      # Forces pulling 'never' or 'ifnotpresent' so it uses the locally built image
      imagePullPolicy: "Never"
      disableNetworking: false
      cmd: ["/bin/bash"]
      resources:
        memory: 512M

# Simple internal authentication allowing any username/password combination
auth:
  password:
    enable: true