ssh:
  hostkeys:
    - "/etc/containerssh/host.key"

backend: docker

log:
  level: "debug"

docker:
  connection:
    host: "unix:///var/run/docker.sock"
  execution:
    container:
      # image: containerssh/agent:latest
      image: "attack_playground_image:latest"
      imagePullPolicy: "Never"
      keepAlive: true
      disableNetworking: false
        # cmd: ["/bin/sh"]
      disableAgent: true
      resources:
        memory: 512M

auth:
  password:
    method: webhook
    webhook:
      url: "http://containerssh-auth:8080/auth"
